In [47]:
import numpy as np

In [48]:
zahlen = np.arange(100) 
quadrate = zahlen ** 2
quadrate.sum()

np.int64(328350)

In [49]:
# Zufallszahlengenerator 

rng = np.random.default_rng(1) # Seed festlegen für Reproduzierbarkeit
heights = rng.normal(170, 10, 1000) # 1000 Werte, normalverteilt mit mu = 170 und sigma = 10

# Maske = boolesche Arrays 
maske = heights > 190
maske.sum() # Anzahl der Großen
maske.mean() # Mittwert der Maske = Anteil
heights[maske] # Alle Elemente, die die Maske erfüllen
heights[~maske] # Alle Elemente, die die Maske nicht erfüllen

array([173.45584192, 178.21618144, 173.30437076, 156.96842768,
       179.05355867, 174.46374572, 164.63046765, 175.81118104,
       173.64572396, 172.94132497, 170.28422241, 175.46712987,
       162.63545913, 168.37090052, 165.17880687, 175.98846213,
       170.39722107, 167.07543249, 162.18091538, 167.42807759,
       170.08142181, 167.24397095, 182.94063814, 180.06724315,
       142.88837521, 151.10986754, 168.25227908, 165.77809588,
       172.13642997, 172.17321931, 158.87979237, 166.22394993,
       176.46702996, 176.63063372, 164.85993628, 153.51924829,
       171.67464744, 171.09014088, 157.72647946, 163.16773338,
       169.2795632 , 160.55248377, 169.01730032, 170.95483027,
       170.35586237, 164.93708342, 175.93748072, 178.91166954,
       173.20848305, 161.81769773, 177.31652284, 164.98559982,
       178.79160618, 159.28212583, 179.14467203, 169.79936545,
       157.5125111 , 166.86100528, 170.54102279, 172.72791339,
       160.17811875, 158.92626953, 171.99584533, 165.33250383,
       172.35505612, 177.59519522, 153.51212634, 172.54388117,
       182.24646968, 167.02473156, 161.89185417, 177.52243827,
       172.53446516, 178.95883071, 166.5478429 , 155.18181726,
       168.89989235, 165.54171847, 177.75323822, 171.93632848,
       153.69150768, 158.0483692 , 178.83789037, 176.79765017,
       163.59756634, 169.98951203, 174.45573554, 174.68404336,
       178.76242196, 172.56485627, 169.05171661, 167.41151935,
       180.55742801, 147.49145725, 168.61344675, 170.33000104,
       155.74651039, 173.32813613, 163.48718988, 178.62444796,
       168.74407916, 176.69153241, 182.18843605, 173.82929583,
       161.24278857, 154.85681368, 187.53384118, 168.88707807,
       163.11435052, 171.44257088, 168.0858867 , 178.52142264,
       170.33928182, 170.13749584, 162.85420279, 174.69568099,
       159.66133278, 176.6588944 , 185.23937513, 154.75313962,
       145.33770769, 176.16878755, 159.99075151, 157.49304241,
       175.88968934, 161.5927841 , 164.93974516, 166.51882533,
       175.32002086, 165.94697639, 172.7788284 , 168.23466741,
       161.55328896, 166.80173742, 160.49600335, 170.06514986,
       158.76133772, 159.07105631, 184.56961815, 169.4681578 ,
       169.46097975, 175.1153642 , 165.79142997, 167.71464633,
       174.25148735, 172.82415842, 158.40703273, 178.33342597,
       164.09565057, 159.4392105 , 160.9952493 , 166.09454656,
       186.27300255, 158.24464095, 171.60075893, 148.62175642,
       169.98433067, 178.99566417, 167.63336678, 163.70645076,
       172.31511064, 177.00151751, 176.63657571, 189.72473854,
       172.09167472, 164.075899  , 168.7402081 , 169.27501454,
       171.08737383, 169.69972187, 171.73965939, 153.29149939,
       178.29628956, 164.25260731, 158.26841304, 176.3775116 ,
       183.17326007, 174.93028149, 171.61159314, 160.67779695,
       178.80258621, 158.6070533 , 162.20362084, 170.86979249,
       154.45268868, 171.68630407, 165.40928444, 182.262706  ,
       179.62154664, 142.88714563, 170.41702586, 153.825325  ,
       181.09637999, 171.68105869, 175.48405452, 159.34875271,
       188.28430238, 159.35228957, 173.72815122, 163.26697572,
       169.76430063, 157.34363021, 188.67145515, 160.30820489,
       167.03916185, 175.01482931, 163.52439322, 167.6068757 ,
       164.36360154, 168.66539245, 158.29457365, 165.62011924,
       167.93107075, 166.66273996, 170.56689955, 167.06897781,
       177.53211408, 166.76804074, 168.63350404, 163.35218664,
       164.7348516 , 157.35507209, 175.18784921, 158.57481982,
       162.54143602, 173.59244652, 174.02573366, 165.99885249,
       149.8073419 , 174.20513287, 172.59563459, 155.87618785,
       177.70322083, 162.989002  , 158.73811884, 170.95730711,
       168.21529569, 172.02624001, 153.94251942, 188.12230116,
       163.97341385, 154.60340692, 176.18842189, 166.4519587 ,
       173.24858486, 166.60391569, 169.4025964 , 172.45772844,
       162.53347116, 176.78739596, 165.30099901, 161.30312856,
       170.77032422, 174.45041278, 167.70920658, 161.37480213,
       176.19785566, 152.39671208, 159.69135864, 170.39522891,
       156.38940602, 170.27994264, 169.45136882, 178.98739789,
       160.85209648, 163.74093476, 173.33181685, 145.4243641 ,
       163.0134927 , 162.70164947, 178.61127511, 169.60168159,
       152.20571381, 176.2692738 , 178.55377834, 165.50053727,
       167.18399642, 174.85984597, 160.9121975 , 174.38388564,
       171.9929851 , 163.25067384, 156.07898126, 167.74394169,
       161.24577742, 180.01410226, 171.44085368, 177.82084523,
       171.34621935, 172.62901117, 162.17001083, 176.68047427,
       187.84698274, 166.90312444, 164.07225472, 168.42163298,
       165.18719716, 162.98520701, 171.38193644, 167.09082467,
       184.38873594, 170.00201643, 173.23911978, 179.52021868,
       166.99244147, 184.3673654 , 163.67305787, 161.91672298,
       166.33732981, 168.85282608, 155.986818  , 169.64905216,
       153.3251341 , 183.92138401, 169.19003049, 163.58042275,
       160.91661882, 166.15569526, 167.76920532, 159.55489034,
       160.80204906, 168.12824995, 164.79216252, 179.39213104,
       181.37870374, 170.16021204, 174.73599572, 156.64811626,
       176.37417709, 169.6941653 , 174.84668316, 186.00356132,
       147.19142244, 172.60948179, 159.00880937, 175.92196691,
       156.86686563, 165.04600433, 172.02733756, 176.13509386,
       170.74794089, 162.07169061, 164.46467782, 178.84502891,
       169.94500384, 153.16185603, 178.43662708, 174.1624848 ,
       178.73415545, 166.63372534, 178.28156518, 159.3893508 ,
       175.69999811, 165.0961969 , 176.74351705, 180.05644116,
       162.64009848, 169.48770521, 170.38954626, 181.89664818,
       177.10558091, 157.80722456, 174.57608261, 177.45089209,
       153.20850903, 164.636477  , 183.33371188, 156.44929701,
       158.00539416, 175.17082195, 180.18408661, 163.31319513,
       175.40127172, 171.16955269, 185.18749034, 169.9848156 ,
       179.90247312, 160.96882141, 168.15121151, 169.03295546,
       181.39107947, 175.7961304 , 162.48246869, 176.81967764,
       177.70631276, 168.88354278, 167.42337685, 168.06196755,
       153.05007594, 171.88743008, 172.34577929, 161.34471476,
       177.4244625 , 156.27033064, 164.48187179, 165.24780931,
       189.87509832, 154.00815937, 175.62630255, 179.42123278,
       173.77725564, 181.81807944, 159.97262313, 147.19741398,
       177.66817889, 158.04171835, 166.73600123, 158.21154003,
       180.52341857, 178.65150235, 162.79936338, 179.03491845,
       171.21277259, 168.60611169, 170.57416662, 167.9725064 ,
       176.15005264, 173.1034757 , 166.50532854, 180.06255746,
       163.88524385, 172.86933643, 174.22155371, 184.7880706 ,
       164.94558637, 187.43082446, 171.76164952, 168.06023089,
       163.27527249, 175.86293419, 170.48935244, 158.96390734,
       158.72112824, 164.44480792, 163.23993996, 180.90302392,
       183.75538298, 178.68559624, 173.5786889 , 165.71761792,
       170.54483211, 178.84707006, 179.12899205, 167.19587856,
       170.38025076, 165.17455099, 162.17601424, 168.15757998,
       171.95614692, 188.35901587, 170.5203247 , 183.57358075,
       187.67489081, 170.7880787 , 186.07798888, 177.14935405,
       165.82464705, 172.65180025, 170.22877818, 167.6766097 ,
       168.01218767, 171.44209303, 174.3418114 , 161.15118125,
       169.90612338, 154.77644978, 172.60795499, 176.23599476,
       171.63954838, 172.85853152, 175.89943104, 163.34899156,
       167.60951141, 175.10922044, 180.01885735, 173.94921401,
       169.08639428, 179.99660429, 182.66727678, 168.66230154,
       161.79487118, 158.17397072, 171.62277   , 181.10291955,
       172.71668399, 171.72856075, 166.20786117, 175.61029733,
       148.64168949, 172.32373251, 170.2812631 , 156.29659753,
       156.12586768, 159.22479503, 157.99136892, 181.10367802,
       161.11915139, 176.68656413, 175.87510153, 172.59670411,
       156.92421093, 163.87893622, 186.7311497 , 157.09245601,
       161.6834504 , 168.37753477, 178.08990072, 172.51639191,
       177.42044159, 159.32705767, 179.44776594, 175.69028817,
       154.05435445, 185.39916208, 162.31422643, 170.55652817,
       183.97422583, 155.18759771, 150.10139681, 157.03055878,
       164.32933214, 164.21557788, 176.07347174, 172.68536372,
       157.53922735, 175.6737997 , 188.74081342, 181.97054279,
       179.91107448, 170.20177929, 179.83631395, 160.3386718 ,
       177.51014637, 169.12751581, 181.30905698, 174.66010551,
       159.10120214, 171.27992953, 182.1822147 , 158.70766115,
       164.40860122, 162.31326992, 155.0435406 , 179.61268275,
       183.10997303, 178.00043207, 172.42570315, 169.47968616,
       172.39380301, 162.68444083, 178.938456  , 180.45492324,
       179.32543534, 164.69051782, 170.78404342, 168.34219181,
       187.88574788, 171.79696202, 151.17929106, 173.98505651,
       188.82266249, 176.85175716, 178.7947971 , 170.36061267,
       150.28610514, 151.89742246, 157.54052225, 168.73167963,
       173.09998496, 176.89414152, 166.59541957, 179.56929258,
       167.20251242, 162.95510485, 178.51641715, 160.85555017,
       142.70915069, 159.40043241, 170.94159546, 139.19822241,
       166.42861954, 166.67909641, 155.73544031, 155.17496535,
       165.37538052, 164.5289983 , 182.59918509, 173.74863045,
       154.19144554, 161.4534853 , 177.05141527, 188.95976769,
       173.86499494, 173.10712545, 188.60752464, 169.77328556,
       166.90899042, 155.86751218, 164.86983918, 155.78258608,
       170.11191707, 155.91672572, 171.28475748, 178.87647203,
       167.5635068 , 177.3034727 , 177.20843826, 174.47024816,
       187.16247999, 177.78837554, 166.95040434, 163.19176452,
       161.54693652, 174.75867438, 166.76278186, 188.42447606,
       167.85476   , 166.70868746, 186.90176553, 151.16640219,
       165.48448941, 179.50756951, 160.87902429, 165.23170027,
       166.48858834, 176.60808497, 171.37526885, 174.0208741 ,
       175.95283725, 170.29938228, 181.10566198, 162.71041129,
       155.63878504, 152.23128195, 153.78990221, 164.4948427 ,
       180.30046893, 171.74166757, 164.0145339 , 159.30144407,
       164.71114349, 165.96333615, 164.34900609, 155.67455679,
       165.24192179, 180.17136133, 148.25391058, 167.59391328,
       148.78651645, 171.83047611, 162.52510609, 149.14312332,
       171.0070219 , 188.17405354, 171.08891533, 181.61791484,
       169.28495598, 148.42409172, 174.90483491, 165.81720693,
       155.37915072, 177.84836674, 172.86857565, 164.74590359,
       178.68069425, 161.27928032, 176.43432339, 160.59539531,
       175.33954762, 158.99252055, 184.89188203, 172.543075  ,
       184.32875116, 161.77554022, 165.23897627, 178.39664799,
       142.56282852, 159.33209145, 180.33176952, 174.65109324,
       179.78769342, 166.90239113, 175.63999382, 162.6915573 ,
       156.28039632, 153.05205026, 164.48290429, 164.51058578,
       163.70622602, 134.51195029, 150.013964  , 164.67367511,
       172.87016628, 164.21207375, 161.231028  , 146.91526667,
       158.98888721, 186.83396638, 185.60685917, 172.73929066,
       164.27390595, 171.32215531, 158.46958026, 172.60730127,
       170.02952148, 175.31968268, 179.50436849, 187.32838487,
       166.11684165, 180.43388418, 162.08330419, 161.05435052,
       163.81943565, 160.18034344, 179.80264318, 179.23241138,
       182.72311747, 169.74699671, 172.74381596, 164.21573001,
       158.49038752, 174.47018151, 172.68373111, 158.92986735,
       175.85332467, 152.58272657, 168.21001516, 163.69686163,
       164.70723784, 159.16542245, 179.52494091, 175.65948212,
       181.83420267, 171.30497349, 157.01946346, 166.20998482,
       158.08482195, 174.46795165, 181.98705929, 173.16090392,
       163.87479086, 166.16672878, 171.90450003, 155.39642606,
       171.34602143, 171.83497878, 164.39757124, 165.65964733,
       171.53844643, 161.61711153, 161.59537206, 177.59970864,
       172.0337072 , 186.58663601, 159.92022001, 151.99034151,
       179.18778884, 179.34144419, 162.37816674, 155.07142987,
       169.27809409, 152.22094611, 166.31035353, 147.890878  ,
       167.32054236, 148.4864973 , 167.31160399, 184.84511261,
       166.99304774, 177.35238582, 163.22923255, 160.71516961,
       154.64921626, 180.02308463, 169.03020269, 185.82318268,
       157.8018149 , 167.34907599, 170.36186788, 183.68171699,
       187.76934651, 163.05406642, 158.19716088, 152.16154522,
       182.88723169, 168.64005769, 163.02523086, 168.98559993,
       143.91091527, 152.23366974, 178.83802287, 173.44032554,
       170.98079493, 159.4631309 , 175.35345049, 187.25905326,
       157.22731764, 169.61836871, 165.11816272, 173.07611835,
       169.60574787, 167.99380045, 160.64184653, 169.30414746,
       163.31708841, 167.99603421, 168.82486223, 176.0029552 ,
       163.63682668, 166.22579797, 180.17966902, 167.27672804,
       166.84035779, 178.10270147, 172.18526185, 170.37242624,
       171.66195485, 157.06979694, 174.08203649, 182.73797967,
       175.29916444, 153.93822939, 172.35260298, 160.47275082,
       167.26660375, 170.8390972 , 157.62969477, 182.9210544 ,
       168.88338341, 177.5040639 , 175.93479859, 183.03356671,
       181.51768374, 154.8683981 , 170.04810903, 148.27594483,
       165.16223018, 176.78422686, 178.78296653, 182.53825958,
       165.8822235 , 172.85964081, 170.63673631, 182.33686812,
       185.55299991, 166.08466701, 169.63959266, 166.01111567,
       175.67840037, 177.27192385, 175.15614255, 163.20323366,
       184.43800972, 170.25823864, 185.10470167, 183.66561862,
       157.01144771, 159.95686873, 159.75766862, 172.27077561,
       170.32114123, 172.4757524 , 161.67289191, 174.07147366,
       183.8510461 , 156.46405285, 167.86204756, 172.31005755,
       168.52949421, 167.85872555, 187.52263985, 182.67067505,
       178.33394943, 162.22800437, 173.45902663, 164.07024057,
       166.47622719, 164.95671381, 171.91186976, 170.49319683,
       148.33387841, 177.23810252, 159.28504043, 158.57043366,
       175.99557698, 161.23591483, 178.22834951, 181.08893088,
       151.9760508 , 168.50889965, 154.13182031, 169.25066017,
       178.99197979, 156.23172634, 187.89159811, 166.75358861,
       158.024322  , 168.60682648, 177.76774728, 156.07066704,
       169.85734039, 156.10187504, 181.87546172, 171.37872893,
       165.57315146, 180.17486474, 156.9338874 , 165.88313206,
       188.27518567, 168.5693362 , 183.37560931, 171.7573595 ,
       162.80375038, 167.33778629, 170.56934042, 165.69986284,
       161.5529827 , 161.97608322, 154.95532063, 170.8910327 ,
       173.72080845, 177.27299902, 151.72413754, 177.83867722,
       169.60893927, 155.49384048, 170.75835112, 177.92594811,
       175.00420731, 177.03327238, 179.23334435, 178.73957255,
       169.42549951, 148.95769392, 162.18768428, 173.34596138,
       165.09127179, 176.64382208, 177.76818105, 170.27355611,
       188.59187102, 160.04467058, 179.11058333, 165.07413997,
       161.99533686, 175.6881527 , 163.64386231, 178.39288982,
       158.13706313, 170.15583934, 161.37070078, 167.4552194 ,
       166.08588658, 158.52030619, 176.36279666, 157.35756459,
       160.00910433, 178.72751169, 179.54740351, 176.49445275,
       173.22040591, 157.72594588, 162.39011819, 159.88722546,
       178.81458832, 172.71009947, 180.93985933, 179.55762332,
       167.58375042, 161.64603332, 159.91550035, 179.51823347,
       175.77532009, 166.45669558, 167.86601829, 166.40907864,
       166.61215171, 145.81500631, 169.23800583, 166.02866333,
       172.74956323])

In [50]:
# Linspace 
x = np.linspace(0, 10, 100) # 0 ... Anfang, 10 ... Ende (gehört dazu)
# 100 Punkte insgesamt 
x.shape, x.dtype,x.min(), x.max()

((100,), dtype('float64'), np.float64(0.0), np.float64(10.0))

In [51]:
# %pip install pandas

In [ ]:
import pandas as pd

df = pd.read_csv("data/versicherte.csv") # df ... DataFrame 
#df.info()
df.tail(7) # head ... die ersten, tail ... die letzten

,versicherten_nr,vorname,nachname,geburtsdatum,alter,geschlecht,plz,stadt,bundesland,beruf,blutgruppe,raucher,groesse_cm,gewicht_kg,bmi,arztbesuche_jahr,leistungsausgaben_eur,zusatzversicherung
5018,U227346012,Frank,Klein,1964-09-13,61,männlich,39361,Magdeburg,Sachsen-Anhalt,ohne Beschäftigung,0-,False,180,73.6,22.7,1,1156.06,False
5019,X366481593,Manfred,Krüger,1950-03-29,76,männlich,10921,Berlin,Berlin,Rente,0-,False,185,79.2,23.1,12,2435.95,False
5020,B141140522,Jana,Weber,1992-06-30,34,weiblich,18949,Rostock,Mecklenburg-Vorpommern,ohne Beschäftigung,0+,True,176,85.4,27.6,10,1420.91,False
5021,V591790861,Jörg,Klein,1965-08-29,61,männlich,30971,Hannover,Niedersachsen,Finanzen,0-,True,186,99.3,28.7,4,6963.77,False
5022,G857070883,Jürgen,Kaya,1951-12-03,74,männlich,45346,Essen,Nordrhein-Westfalen,Rente,0+,False,182,102.8,31.0,6,10233.96,False
5023,U226070405,Hans,Schäfer,1961-11-09,64,männlich,10257,Berlin,Berlin,Rente,A+,False,183,98.3,29.4,3,10286.15,False
5024,A732408901,Gisela,Fischer,1961-03-12,65,weiblich,30015,Hannover,Niedersachsen,Rente,A+,False,164,68.9,25.6,10,6893.28,False

In [53]:
df.alter # Spaltenbasierter Zugriff 
df["alter"] # dasselbe 

# Wichtige Zugriff: loc (namentlich) und iloc (indexbasiert)
spalten = ["vorname", "nachname", "stadt"]
mit_loc = df.loc[10:20, spalten]
mit_loc

      vorname nachname       stadt
10      Laura    Bauer     Leipzig
11      Jonas    Bauer      Berlin
12  Katharina     Wolf     Hamburg
13      Karin    Meyer     Hamburg
14      Klaus   Krüger     Hamburg
15     Thomas  Fischer      Bremen
16      Klaus    Weber   Stuttgart
17      Frank   Müller  Düsseldorf
18   Stefanie  Schäfer      Berlin
19     Günter  Lehmann     Hamburg
20       Lisa   Becker      Erfurt

In [54]:
# dasselbe mit iloc 
mit_iloc = df.iloc[10:21, [1,2,7]] # indexbasiert angeben, Ende 21 gehört nicht dazu
mit_iloc

      vorname nachname       stadt
10      Laura    Bauer     Leipzig
11      Jonas    Bauer      Berlin
12  Katharina     Wolf     Hamburg
13      Karin    Meyer     Hamburg
14      Klaus   Krüger     Hamburg
15     Thomas  Fischer      Bremen
16      Klaus    Weber   Stuttgart
17      Frank   Müller  Düsseldorf
18   Stefanie  Schäfer      Berlin
19     Günter  Lehmann     Hamburg
20       Lisa   Becker      Erfurt

In [55]:
# mit Maske filtern 
# männliche Raucher mit BMI > 30 
# in numpy und pandas & ... für und, | ... für oder, ~ ... für nicht
maske = (df["geschlecht"] == "männlich") &  (df["bmi"]>30) & (df["raucher"])
df[maske]

# mit Query (SQL-ählich oder SQL-like)
query = df.query("geschlecht == 'männlich' and bmi > 30 and raucher")
query

,versicherten_nr,vorname,nachname,geburtsdatum,alter,geschlecht,plz,stadt,bundesland,beruf,blutgruppe,raucher,groesse_cm,gewicht_kg,bmi,arztbesuche_jahr,leistungsausgaben_eur,zusatzversicherung
19,Y774461550,Günter,Lehmann,1927-06-19,99,männlich,20665,Hamburg,Hamburg,Rente,A+,True,185,113.1,33.0,4,2801.80,False
278,W659812037,Wolfgang,Schäfer,1947-11-20,78,männlich,30555,Hannover,Niedersachsen,Rente,A+,True,176,102.7,33.2,2,4085.94,False
295,F909085442,Horst,Nowak,1936-12-25,89,männlich,30166,Hannover,Niedersachsen,Logistik,0+,True,183,100.8,30.1,11,21916.56,False
320,W905780246,Michael,Hartmann,1967-05-08,59,männlich,44309,Dortmund,Nordrhein-Westfalen,NaN,0+,True,185,109.0,31.8,3,48064.15,True
541,S599957556,Andreas,Lange,1966-12-07,59,männlich,40930,Düsseldorf,Nordrhein-Westfalen,Pflege,A+,True,191,109.8,30.1,7,2350.24,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4887,E372116923,Stefan,Nowak,1989-08-08,37,männlich,55010,Mainz,Rheinland-Pfalz,Verwaltung,A+,True,175,92.3,30.1,27,5365.03,False
4937,E483685277,Jörg,Hofmann,1966-12-02,59,männlich,30360,Hannover,Niedersachsen,Einzelhandel,B+,True,194,117.2,31.1,1,1470.69,False
4945,N206415738,Werner,Müller,1958-09-28,67,männlich,30008,Hannover,Niedersachsen,Rente,0+,True,188,118.1,33.4,2,5539.59,False
4954,V132775264,Andreas,Richter,1979-07-03,47,männlich,80057,München,Bayern,Ingenieurwesen,A+,True,182,115.5,34.9,15,2656.10,False
5010,D785653966,Peter,Hoffmann,1958-03-07,68,männlich,10495,Berlin,Berlin,Rente,NaN,True,167,92.7,33.2,11,4504.15,False

In [57]:
# Altersgruppen und bmi_klasse mit pd.cut

df["altersgruppe"] = pd.cut(df["alter"], bins= [0, 18, 65, 120],
                           labels=["Kind", "Erwachsen", "Senior"], right=False)
# right = False -> rechte Grenze gehört nicht dazu

# TODO BMI 
# unter 18.5 -> Untergewicht
# >=18.5 aber unter 25 -> Normalgewicht
# >= 25 aber unter 30 -> Übergewicht
# >= 30 -> Adipositas 
df["bmi_klasse"] = pd.cut(df["bmi"], bins=[0, 18.5, 25, 30, 100],
                          labels=["Untergewicht", "Normalgewicht", "Übergewicht", "Adipositas"],
                          right=False)


df["altersgruppe"].value_counts() # Zählen 
df["bmi_klasse"].value_counts(dropna=False)

bmi_klasse
Übergewicht      2004
Normalgewicht    1875
Adipositas        892
NaN               154
Untergewicht      100
Name: count, dtype: int64